# Generated by Django 5.2 on 2025-10-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
