# Generated by Django 5.2 on 2025-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_image_alter_teammember_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='member_images/'),
        ),
    ]
